### ISSUE TITLE
Buy Internet subscription 

### ISSUE THREAD

**Issue by surajssd** [mvpride001/housekeeping#4]

**Comment by aditya-konarde** [comment]
Needs discussion. How many lines? Do we have a plan for failover?

**Comment by surajssd** [comment]
It's a room specific thing so I think we can close this.

WDYT? @aditya-konarde @rootAvish @surajnarwade  ?

**Comment by rootAvish** [comment]
Makes sense.

**Comment by surajssd** [comment]
even this is done
