### ISSUE TITLE
Get a washing machine 

### ISSUE THREAD

**Issue by surajssd** [mvpride001/housekeeping#5]
Budget limit 10k

**Comment by aditya-konarde** [comment]
+1. Also make sure that the washing machine is fully automatic. We've done some initial capacity planning and a basic washing machine that holds ~7kg looks good.

**Comment by surajssd** [comment]
This is partially done thanks to @surajnarwade and @abs51295 now the setup is what is remaining

**Comment by surajssd** [comment]
we got one i guess
